# -*- coding: utf-8 -*-
"""Virtual TheraSpist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11HI-LXEPSKyIPrMIZk4g9HiA54J2NN_P
"""

#Import the libraries
import re
import random

response={
    "hello":["Hello,how can i help you"],
    "i feel (.*)":["Why do you feel {}?", "How long have you been feeling {}?"],
    "i am (.*)":["Why do you say you're {}?","How long have you been {}?"],
    "i am (.*)":["Why are you {}?", "How long have you been {}?"],
    "i (.*) you":["Why do you {} me ?", "What makes you think you {} me?"],
    "i (.*) myself":["Why do you {} yourself","What makes you think you {} yourself?"],
    "(.*)sorry (.*)":["There's no need to applogize","What are you applogizing for?"],
    "(.*) friend (.*)":["Tell me more about your friend.","How do your friends make you feel?"],
    "yes":["You seem quite sure.", "Ok, but can you elaborate."],
    "no":["Why not?","Ok, but can you elaborate a bit?"],
    "(.*) ":["Please tell me more ","let's chamge focus a bit...tell me about your family.","Can you elaborate on that?"],
    "":["Why do you think that?", "Let's change focus a bit...tell me about your family", "Can you elaborate on that?"],

}

#Define a function  to match the user's input to a pre-defined response
def match_response(input_text):
  #Create a loop to iterate over the items of the "response" dictionary.
  for pattern, response_list in response.items():
    matches=re.match(pattern ,input_text.lower())
    if matches:
      chosen_response =random.choice(response_list)
      return chosen_response.format(*matches.groups())
#There is no pattern so return .
      return "I'm sorry I don't understand what you're saying."

#Create the main loop to start the chatbot.
print("Welcome to Shresth's Psyscotherepist Chatbot")
while True:
  user_input= input("You: ")
  if user_input.lower() == "bye":
    print("Shresth's: Goodbye.")
    break
  else:
    print("Shresth's: "+match_response(user_input))

